# Generated by Django 4.1.4 on 2022-12-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_topbar_rename_topbanner_mainbanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_level_code',
            new_name='course_code',
        ),
    ]
