# Generated by Django 4.1.4 on 2022-12-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_course_level_code_course_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_outline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='tech_subs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='what_you_will_learn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
