# Generated by Django 4.1.4 on 2022-12-29 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_schedule_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='techicon',
            name='icon_img',
        ),
        migrations.AddField(
            model_name='featuredproject',
            name='student_pic',
            field=models.ImageField(blank=True, null=True, upload_to='studentprojectpic/'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sectionbanner',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techicon',
            name='icon_img_src',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topbar',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NavLinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250)),
                ('item_url', models.CharField(max_length=150)),
                ('navlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.navlink')),
            ],
        ),
    ]
