# Generated by Django 4.1.4 on 2022-12-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_techicon_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShortQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=50)),
                ('tartiary_education', models.CharField(max_length=50)),
                ('tartiary_studied', models.CharField(max_length=150)),
                ('secondary_sch', models.CharField(max_length=150)),
                ('secondary_studied', models.CharField(max_length=150)),
                ('tech_interest', models.CharField(max_length=150)),
                ('more_about_you', models.TextField()),
            ],
        ),
    ]
