# Generated by Django 4.1.4 on 2023-01-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_featuredproject_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='registration_status',
            field=models.BooleanField(default=True),
        ),
    ]
