# Generated by Django 4.1.4 on 2023-01-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_schedule_registration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techicon',
            name='icon_img_src',
        ),
        migrations.AddField(
            model_name='techicon',
            name='icon_img',
            field=models.ImageField(null=True, upload_to='techicons/'),
        ),
    ]
