# Generated by Django 4.1.4 on 2023-01-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_resourcetype_resource_project_enrollment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="cheat_sheat",
            field=models.FileField(blank=True, null=True, upload_to="free/cheat_sheat"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="primer",
            field=models.FileField(blank=True, null=True, upload_to="free/primer"),
        ),
    ]
