# Generated by Django 4.1.4 on 2023-01-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_resource_cheat_sheat_alter_resource_primer"),
        ("api", "0011_remove_techicon_icon_img_src_techicon_icon_img"),
    ]

    operations = []
