# Generated by Django 4.1.4 on 2023-01-13 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_merge_20230112_1230"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestedForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=155)),
                ("email", models.EmailField(max_length=155)),
                ("mobile", models.CharField(max_length=50)),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
            ],
        ),
    ]
