# Generated by Django 4.1.4 on 2023-01-15 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_interestedform"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[("Absent", "Absent"), ("Present", "Present")],
                        default="Absent",
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("attendance_comment", models.CharField(max_length=255)),
                ("raise_warning", models.BooleanField(default=False)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.batch"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.student"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.teacher"
                    ),
                ),
            ],
        ),
    ]
