# Generated by Django 4.1.4 on 2023-01-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_studentattendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentattendance",
            name="teacher",
        ),
        migrations.AlterField(
            model_name="course",
            name="location_state",
            field=models.CharField(
                blank=True, default="Lagos", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="location_state_area",
            field=models.CharField(
                blank=True, default="Ikeja", max_length=50, null=True
            ),
        ),
    ]
