# Generated by Django 4.1.4 on 2023-01-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_student_user_teacher_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="student_id",
            new_name="student_idcard_id",
        ),
        migrations.RemoveField(
            model_name="student",
            name="email_addresses",
        ),
        migrations.RemoveField(
            model_name="student",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="last_name",
        ),
        migrations.AddField(
            model_name="teacher",
            name="teacher_idcard_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
