# Generated by Django 4.1.4 on 2023-01-17 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_coursemanual_batch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursemanual",
            name="batch",
        ),
        migrations.AddField(
            model_name="coursemanual",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.enrollment",
            ),
        ),
    ]
