# Generated by Django 4.1.4 on 2023-01-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_remove_project_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignmentallocation",
            old_name="asssignment",
            new_name="assignment",
        ),
    ]
