# Generated by Django 4.1.4 on 2023-01-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_rename_asssignment_assignmentallocation_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="prerequisites",
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
    ]
