# Generated by Django 4.1.4 on 2023-01-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_course_prerequisites"),
    ]

    operations = [
        migrations.CreateModel(
            name="KidsCoding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.CharField(max_length=50)),
                (
                    "age_bracket",
                    models.CharField(
                        choices=[("1", "6-9"), ("2", "10-14")], max_length=150
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VirtualClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.CharField(max_length=50)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
            ],
        ),
    ]
