# Generated by Django 4.1.4 on 2023-01-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_course_kids_coding_coursecategory_child_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="batch",
            field=models.CharField(max_length=255),
        ),
    ]
