# Generated by Django 4.1.4 on 2023-01-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_rename_pic1_course_pic1_detailpage_banner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kidscoding",
            name="age_bracket",
            field=models.CharField(
                choices=[("6-9", "6-9"), ("10-14", "10-14")], max_length=150
            ),
        ),
    ]
