# Generated by Django 4.1.4 on 2023-01-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_resource_short_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kidscoding",
            name="age_bracket",
            field=models.CharField(
                choices=[("1", "6-9"), ("2", "10-14")], max_length=150
            ),
        ),
    ]
