# Generated by Django 4.1.4 on 2023-01-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_kidscoding_age_bracket"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcetype",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
