# Generated by Django 4.1.4 on 2023-01-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_resourcetype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, null=True),
        ),
    ]
