# Generated by Django 4.1.4 on 2023-01-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_resourcetype_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("teacher", "Teacher"), ("student", "Student")],
                default="",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="prerequisites",
            field=models.TextField(blank=True, null=True),
        ),
    ]
