# Generated by Django 4.1.4 on 2023-01-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
