# Generated by Django 4.1.4 on 2023-01-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_user_user_type_alter_course_prerequisites"),
        ("api", "0032_mainbanner_ordering"),
    ]

    operations = []
