# Generated by Django 4.1.4 on 2023-02-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_remove_mainbanner_ordering_course_course_outline_pdf_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="active",
            new_name="published",
        ),
    ]
