# Generated by Django 4.1.4 on 2023-02-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_alter_course_course_outline_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_outline_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="courseoutline/files"
            ),
        ),
    ]
