# Generated by Django 4.1.4 on 2023-02-08 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_alter_course_course_outline_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternationalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=255)),
                (
                    "flag",
                    models.ImageField(
                        upload_to="international/flags",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("country_code", models.CharField(max_length=255)),
                ("topbar_src", models.TextField()),
                ("intro_txt", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="is_virtual_class",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schedule",
            name="fee_dollar",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="naira_to_dollar_rate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="program_type",
            field=models.CharField(
                blank=True,
                choices=[("physical", "Physical Class"), ("virtual", "Virtual Class")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="virtualclass",
            name="country_of_residence",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
