# Generated by Django 4.1.4 on 2023-02-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_internationalmodel_course_is_virtual_class_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="naira_to_dollar_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
