# Generated by Django 4.1.4 on 2023-02-09 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_alter_schedule_fee_dollar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="fee_dollar",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="naira_to_dollar_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
