# Generated by Django 4.1.4 on 2023-02-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_alter_schedule_fee_dollar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="program_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Physical/Onsite", "Physical/Onsite Class"),
                    ("Virtual", "Virtual Class"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
