# Generated by Django 4.1.4 on 2023-02-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_alter_schedule_program_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="program_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Physical/Onsite Class", "Physical/Onsite Class"),
                    ("Virtual/Online Class", "Virtual/Online Class"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
