# Generated by Django 4.1.4 on 2023-02-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_internationalmodel_ordering_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internationalmodel",
            name="ordering",
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
