# Generated by Django 4.1.4 on 2023-02-13 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_alter_internationalmodel_ordering"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumiConnect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("date_posted", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommunityConnect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "community",
                    models.CharField(
                        choices=[("Webinars", "Webinars"), ("Meetups", "Meetups")],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("descriptions", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        upload_to="community/banners",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("start_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="FinancialAid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aid_type",
                    models.CharField(
                        choices=[
                            ("Student Loan", "Student Loan"),
                            ("Full Scholarship", "Full Scholarship"),
                            ("Partial Scholarship", "Partial Scholarship"),
                        ],
                        max_length=50,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("mobile", models.CharField(max_length=50)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="naira_to_dollar_rate",
        ),
        migrations.AddField(
            model_name="mainbanner",
            name="ordering",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
