# Generated by Django 4.1.4 on 2023-02-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_alumiconnect_communityconnect_financialaid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermsOfService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("descriptions", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
