# Generated by Django 4.1.4 on 2023-02-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_termsofservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityconnect",
            name="ordering",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="communityconnect",
            name="past",
            field=models.BooleanField(default=False),
        ),
    ]
