# Generated by Django 4.1.4 on 2023-02-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_communityconnect_ordering_communityconnect_past"),
    ]

    operations = [
        migrations.RenameField(
            model_name="communityconnect",
            old_name="past",
            new_name="completed",
        ),
    ]
