# Generated by Django 4.1.4 on 2023-02-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_rename_past_communityconnect_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course_outline",
        ),
        migrations.RemoveField(
            model_name="course",
            name="extra_note",
        ),
        migrations.RemoveField(
            model_name="course",
            name="requirements",
        ),
        migrations.AlterField(
            model_name="schedule",
            name="fee_dollar",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
