# Generated by Django 4.1.4 on 2023-02-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_remove_course_course_outline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kidscoding",
            name="age_bracket",
            field=models.CharField(
                choices=[("6-9", "6-9"), ("10-14", "10-14")], max_length=150
            ),
        ),
    ]
