# Generated by Django 4.1.4 on 2023-02-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_virtualhowitworks_virtualvsothers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VirtualHowItWorks",
            new_name="VirtualHowItWork",
        ),
        migrations.RenameModel(
            old_name="VirtualVsOthers",
            new_name="VirtualVsOther",
        ),
    ]
