# Generated by Django 4.1.4 on 2023-02-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_rename_virtualhowitworks_virtualhowitwork_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HowItWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "how_it_work_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Physical Class", "Physical Class"),
                            ("Virtual Class", "Virtual Class"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="VirtualHowItWork",
        ),
    ]
