# Generated by Django 4.1.4 on 2023-03-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_howitwork_delete_virtualhowitwork"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("full_name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("social_dump", models.TextField()),
            ],
        ),
    ]
