# Generated by Django 4.1.4 on 2023-03-03 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_ourteam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="assignmentallocation",
            name="student",
        ),
        migrations.AddField(
            model_name="assignmentallocation",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.batch",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.course",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="Enrollment",
        ),
    ]
