# Generated by Django 4.1.4 on 2023-03-08 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_alter_batch_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursemanualallocation",
            name="student",
        ),
        migrations.AddField(
            model_name="coursemanualallocation",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.batch",
            ),
        ),
    ]
