# Generated by Django 4.1.4 on 2023-03-14 02:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import api.validate


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_alter_batch_students_alter_student_profile_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("tagline", models.TextField()),
                (
                    "company_logo",
                    models.ImageField(
                        upload_to="JobPortal/Company",
                        validators=[
                            api.validate.validate_file_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["svg", "jpg", "png", "jpeg"]
                            ),
                        ],
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                (
                    "save_as",
                    models.CharField(
                        choices=[("Draft", "Draft"), ("Published", "Published")],
                        default="Draft",
                        max_length=50,
                    ),
                ),
                ("job_summary", models.TextField()),
                ("job_responsibilities", models.TextField()),
                ("close_job", models.BooleanField(default=False)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.employer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("Experienced", "Experienced"),
                            ("Intermediate", "Intermediate"),
                            ("Internship", "Internship"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Full-time", "Full-time"),
                            ("Part-time", "Part-time"),
                            ("Contractor", "Contractor"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "job_location",
                    models.CharField(
                        choices=[
                            ("On-site", "On-site"),
                            ("Hybrid", "Hybrid"),
                            ("Remote", "Remote"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv_upload",
                    models.FileField(
                        upload_to="JobPortal/cv_upload",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("pdf", "jpg", "jpeg", "png")
                            )
                        ],
                    ),
                ),
                ("years_of_experience", models.CharField(max_length=50)),
                ("date_applied", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.job"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="job_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.jobcategory"
            ),
        ),
    ]
