# Generated by Django 4.1.4 on 2023-03-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_jobapplication_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_sponsor", models.CharField(max_length=255)),
                (
                    "selection",
                    models.CharField(
                        choices=[
                            ("Individual", "Individual"),
                            ("Organisation", "Organisation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("number_of_student", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("remarks", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
