# Generated by Django 4.1.4 on 2023-03-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_sponsorship"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("our_vision", models.TextField()),
                ("our_mission", models.TextField()),
                ("our_mission_item", models.TextField()),
                ("why_anchorsoft", models.TextField()),
                ("ordering", models.CharField(max_length=10)),
            ],
        ),
    ]
