# Generated by Django 4.1.4 on 2023-03-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_sponsorship_organisation_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sponsorship",
            old_name="organisation_name",
            new_name="organization_name",
        ),
        migrations.AlterField(
            model_name="financialaid",
            name="aid_type",
            field=models.CharField(
                choices=[
                    ("Student Loan", "Student Loan"),
                    (
                        "Full Scholarship(Tuition + Laptop + Stipends)",
                        "Full Scholarship(Tuition + Laptop + Stipends)",
                    ),
                    (
                        "Scholarship Tier 1 (Tuition + Laptop)",
                        "Scholarship Tier 1 (Tuition + Laptop)",
                    ),
                    ("Scholarship Tier 2 (Tuition)", "Scholarship Tier 2 (Tuition)"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="sponsorship",
            name="selection",
            field=models.CharField(
                choices=[
                    ("Individual", "Individual"),
                    ("Organization", "Organization"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("employer", "Employer"),
                ],
                max_length=8,
                null=True,
            ),
        ),
    ]
