# Generated by Django 4.1.4 on 2023-03-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_rename_organisation_name_sponsorship_organization_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
