# Generated by Django 4.1.4 on 2023-03-16 14:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_employer_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_responsibilities",
            field=tinymce.models.HTMLField(),
        ),
    ]
