# Generated by Django 4.1.4 on 2023-03-20 12:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0069_alter_jobapplication_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_ref", models.UUIDField(default=uuid.uuid4)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("total_amount", models.CharField(max_length=255)),
                ("outstanding_amount", models.CharField(max_length=50)),
                ("payment_completion_status", models.BooleanField(default=False)),
                ("date_paid", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillingDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.CharField(max_length=255)),
                ("date_paid", models.DateTimeField(auto_now_add=True)),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.billing"
                    ),
                ),
            ],
        ),
    ]
