# Generated by Django 4.1.4 on 2023-03-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0071_alter_billing_outstanding_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="billings",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="api.billing",
            ),
        ),
    ]
