# Generated by Django 4.1.4 on 2023-03-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0072_student_billings"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
