# Generated by Django 4.1.4 on 2023-03-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0073_billing_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("announcement", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("expiration_date", models.DateTimeField()),
                ("is_published", models.BooleanField(default=True)),
            ],
        ),
    ]
