# Generated by Django 4.1.4 on 2023-03-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0074_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
