# Generated by Django 4.1.4 on 2023-03-21 08:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0075_alter_announcement_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="cookie_id",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
