# Generated by Django 4.1.4 on 2023-03-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0079_alter_announcement_expiration_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutussection",
            old_name="our_vision",
            new_name="about_intro",
        ),
    ]
