# Generated by Django 4.1.4 on 2023-03-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0080_rename_our_vision_aboutussection_about_intro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="cookie_id",
        ),
    ]
