# Generated by Django 4.1.4 on 2023-03-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0084_user_mobile_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="total_amount_paid",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
