# Generated by Django 4.1.4 on 2023-03-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0085_billing_total_amount_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="squad_transaction_ref",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
