# Generated by Django 4.1.4 on 2023-03-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0086_billing_squad_transaction_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="payment_completion_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "pending"),
                    ("failed", "failed"),
                    ("success", "success"),
                ],
                default="pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
