# Generated by Django 4.1.4 on 2023-03-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0087_alter_billing_payment_completion_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScholarshipSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scholarship_intro", models.TextField()),
                ("access_text", models.TextField()),
                ("wings", models.TextField()),
            ],
        ),
    ]
