# Generated by Django 4.1.4 on 2023-03-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0088_scholarshipsection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
