# Generated by Django 4.1.4 on 2023-03-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0089_alter_billing_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billingdetail",
            name="outstanding_amount",
        ),
        migrations.AddField(
            model_name="billing",
            name="outstanding_amount",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
