# Generated by Django 4.1.4 on 2023-03-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0091_remove_billingdetail_amount_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingdetail",
            name="amount_paid",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
