# Generated by Django 4.1.4 on 2023-03-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0092_billingdetail_amount_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingdetail",
            name="amount_paid",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
