# Generated by Django 4.1.4 on 2023-03-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0096_albumsection_careersection"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumiConnectSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("intro", models.TextField()),
                ("content", models.TextField()),
            ],
        ),
    ]
