# Generated by Django 4.1.4 on 2023-03-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0098_enrollment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="course",
        ),
        migrations.DeleteModel(
            name="Enrollment",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
