# Generated by Django 4.1.4 on 2023-03-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0100_financialaid_guarantor_full_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentloansection",
            name="how_it_works",
        ),
    ]
