# Generated by Django 4.1.4 on 2023-03-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0101_remove_studentloansection_how_it_works"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialaid",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.course",
            ),
        ),
    ]
