# Generated by Django 4.1.4 on 2023-03-30 14:42

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0105_blogcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("seo_keywords", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("content", tinymce.models.HTMLField()),
                ("image_1", models.ImageField(blank=True, null=True, upload_to="blog")),
                ("image_2", models.ImageField(blank=True, null=True, upload_to="blog")),
                ("image_3", models.ImageField(blank=True, null=True, upload_to="blog")),
                (
                    "status",
                    models.CharField(
                        choices=[("published", "Published"), ("draft", "Draft")],
                        max_length=50,
                    ),
                ),
                (
                    "blog_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.blogcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
                "abstract": False,
            },
        ),
    ]
