# Generated by Django 4.1.4 on 2023-03-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0108_remove_student_billings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="program_type",
            field=models.CharField(
                blank=True,
                choices=[("Onsite", "Onsite"), ("Virtual", "Virtual")],
                max_length=50,
                null=True,
            ),
        ),
    ]
