# Generated by Django 4.1.4 on 2023-03-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0109_alter_schedule_program_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobcategory",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="jobcategory",
            name="job_location",
        ),
        migrations.RemoveField(
            model_name="jobcategory",
            name="job_type",
        ),
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Experienced", "Experienced"),
                    ("Intermediate", "Intermediate"),
                    ("Internship", "Internship"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("On-site", "On-site"),
                    ("Hybrid", "Hybrid"),
                    ("Remote", "Remote"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Full-time", "Full-time"),
                    ("Part-time", "Part-time"),
                    ("Contractor", "Contractor"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="billingdetail",
            name="outstanding_amount",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
