# Generated by Django 4.1.4 on 2023-04-03 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0111_job_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="cv_upload",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="years_of_experience",
        ),
        migrations.AddField(
            model_name="student",
            name="cv_upload",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="JobPortal/cv_upload",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("pdf", "jpg", "jpeg", "png")
                    )
                ],
            ),
        ),
    ]
