# Generated by Django 4.1.4 on 2023-04-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0112_remove_jobapplication_cv_upload_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("student", "job")},
        ),
    ]
