# Generated by Django 4.1.4 on 2023-04-04 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0115_alter_job_options_alter_job_job_summary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-date_posted"]},
        ),
        migrations.AlterModelOptions(
            name="jobapplication",
            options={"ordering": ["-date_applied"]},
        ),
    ]
