# Generated by Django 4.1.4 on 2023-04-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0116_alter_job_options_alter_jobapplication_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InterestedForm",
            new_name="Enrollment",
        ),
    ]
