# Generated by Django 4.1.4 on 2023-04-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0118_batch_program_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employer",
            old_name="full_name",
            new_name="contact_person",
        ),
        migrations.AddField(
            model_name="employer",
            name="company_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employer",
            name="contact_person_mobile",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
