# Generated by Django 4.1.4 on 2023-04-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0119_rename_full_name_employer_contact_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=models.SlugField(),
        ),
    ]
