# Generated by Django 4.1.4 on 2023-04-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0120_alter_job_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
