# Generated by Django 4.1.4 on 2023-04-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0122_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="company_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
