# Generated by Django 4.1.4 on 2023-04-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0123_alter_employer_company_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="job",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="job",
            name="job_category",
        ),
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.ManyToManyField(to="api.jobexperience"),
        ),
        migrations.AddField(
            model_name="job",
            name="job_category",
            field=models.ManyToManyField(to="api.jobcategory"),
        ),
    ]
