# Generated by Django 4.1.4 on 2023-04-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0124_jobexperience_remove_job_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="fee",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="program_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="start_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
