# Generated by Django 4.1.4 on 2023-04-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0125_enrollment_fee_enrollment_program_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="fee_dollar",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
