# Generated by Django 4.1.4 on 2023-04-11 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0126_enrollment_fee_dollar"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.schedule",
            ),
        ),
    ]
