# Generated by Django 4.1.4 on 2023-04-11 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0127_enrollment_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="squad_transaction_ref",
        ),
        migrations.RemoveField(
            model_name="billing",
            name="transaction_ref",
        ),
        migrations.AddField(
            model_name="billing",
            name="got_scholarship",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="billing",
            name="sponsor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.sponsorship",
            ),
        ),
    ]
