# Generated by Django 4.1.4 on 2023-04-11 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0128_remove_billing_squad_transaction_ref_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("name_of_sponsor", models.CharField(max_length=255)),
                (
                    "selection",
                    models.CharField(
                        choices=[
                            ("Individual", "Individual"),
                            ("Organization", "Organization"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("number_of_student", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("remarks", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="billingdetail",
            name="outstanding_amount",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="billing",
            name="sponsor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.sponsor",
            ),
        ),
        migrations.DeleteModel(
            name="Sponsorship",
        ),
    ]
