# Generated by Django 4.1.4 on 2023-04-11 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0129_sponsor_alter_billingdetail_outstanding_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="course_manual",
            field=models.ManyToManyField(to="api.coursemanual"),
        ),
        migrations.CreateModel(
            name="ScholarshipAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("award_date", models.DateTimeField()),
                ("total_amount", models.CharField(max_length=255)),
                ("amount_received", models.CharField(max_length=255)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("date_last_updated", models.DateTimeField(auto_now=True)),
                ("number_of_students", models.PositiveIntegerField()),
                ("remarks", models.TextField()),
                ("beneficiaries", models.ManyToManyField(to="api.student")),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.sponsor"
                    ),
                ),
            ],
        ),
    ]
