# Generated by Django 4.1.4 on 2023-04-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0130_batch_course_manual_scholarshipaward"),
    ]

    operations = [
        migrations.RenameField(
            model_name="batch",
            old_name="course_manual",
            new_name="course_manuals",
        ),
    ]
