# Generated by Django 4.1.4 on 2023-04-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0132_student_just_for_jobs_delete_coursemanualallocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="total_amount",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Total amount of the course"
            ),
        ),
    ]
