# Generated by Django 4.1.4 on 2023-04-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0133_alter_billing_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingdetail",
            name="outstanding_amount",
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
