# Generated by Django 4.1.4 on 2023-04-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0136_alter_billingdetail_outstanding_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingdetail",
            name="outstanding_amount",
            field=models.CharField(default=0, max_length=50),
        ),
    ]
