# Generated by Django 4.1.4 on 2023-04-12 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0139_extraitem_alter_billingdetail_outstanding_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraitem",
            name="billing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.billing",
            ),
        ),
    ]
