# Generated by Django 4.1.4 on 2023-04-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0140_extraitem_billing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employer",
            name="company_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employer",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employer",
            name="tagline",
            field=models.TextField(blank=True, null=True),
        ),
    ]
