# Generated by Django 4.1.4 on 2023-04-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0141_alter_employer_company_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="email",
        ),
        migrations.RemoveField(
            model_name="billing",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="billing",
            name="last_name",
        ),
    ]
