# Generated by Django 4.1.4 on 2023-04-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0143_rename_total_amount_paid_billing_grand_outstanding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingdetail",
            name="course_fee",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
