# Generated by Django 4.1.4 on 2023-04-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0144_billingdetail_course_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraitem",
            name="item_name_fee",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
