# Generated by Django 4.1.4 on 2023-04-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0145_extraitem_item_name_fee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billing",
            old_name="grand_outstanding",
            new_name="total_amount_paid",
        ),
        migrations.RemoveField(
            model_name="billing",
            name="grand_total",
        ),
        migrations.RemoveField(
            model_name="billingdetail",
            name="course_fee",
        ),
        migrations.RemoveField(
            model_name="extraitem",
            name="item_name_fee",
        ),
        migrations.AddField(
            model_name="billing",
            name="total_amount",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Total amount of the course"
            ),
        ),
    ]
