# Generated by Django 4.1.4 on 2023-04-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0149_alter_billingdetail_amount_paid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billingdetail",
            name="program_type",
        ),
    ]
