# Generated by Django 4.1.4 on 2023-04-12 15:46

import api.validate
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0152_remove_billing_course_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="company_logo",
            field=models.ImageField(
                default="JobPortal/Company/loginIcon.png",
                upload_to="JobPortal/Company",
                validators=[
                    api.validate.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg", "jpg", "png", "jpeg"]
                    ),
                ],
            ),
        ),
    ]
