# Generated by Django 4.1.4 on 2023-04-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0153_alter_employer_company_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billing",
            old_name="total_amount_paid",
            new_name="grand_total_paid",
        ),
    ]
