# Generated by Django 4.1.4 on 2023-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0154_rename_total_amount_paid_billing_grand_total_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="billing",
            name="grand_outstanding",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Total amount of the course"
            ),
        ),
    ]
