# Generated by Django 4.1.4 on 2023-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0155_remove_billing_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="grand_outstanding",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
