# Generated by Django 4.1.4 on 2023-04-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0156_alter_billing_grand_outstanding"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExtraItem",
            new_name="BillingExtraPayment",
        ),
    ]
