# Generated by Django 4.1.4 on 2023-04-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0157_rename_extraitem_billingextrapayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_idcard_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
