# Generated by Django 4.1.4 on 2023-04-13 07:56

import api.validate
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0158_alter_student_student_idcard_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("just_for_jobs", models.BooleanField(default=False)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "student_idcard_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "date_of_birth",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "mobile_numbers",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        upload_to="students_profilepix/",
                        validators=[
                            api.validate.validate_file_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "png", "jpeg"]
                            ),
                        ],
                    ),
                ),
                (
                    "cv_upload",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="JobPortal/cv_upload",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("pdf", "jpg", "jpeg", "png")
                            )
                        ],
                    ),
                ),
                (
                    "residential_address",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "contact_address",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "next_of_kin_fullname",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "next_of_kin_contact_address",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "next_of_kin_mobile_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "relationship_with_next_kin",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
