# Generated by Django 4.1.4 on 2023-04-13 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0159_backupstudent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backupstudent",
            name="user",
        ),
        migrations.AddField(
            model_name="backupstudent",
            name="student",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.student",
            ),
        ),
    ]
