# Generated by Django 4.1.4 on 2023-04-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0162_alter_batch_course_manuals"),
    ]

    operations = [
        migrations.AddField(
            model_name="internationalmodel",
            name="identify_our_virutal_courses",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scholarshipsection",
            name="eligibility",
            field=models.TextField(blank=True, null=True),
        ),
    ]
