# Generated by Django 4.1.4 on 2023-04-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0163_internationalmodel_identify_our_virutal_courses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
