# Generated by Django 4.1.4 on 2023-04-13 10:53

import api.validate
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0165_alter_student_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupstudent",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="students_profilepix/",
                validators=[
                    api.validate.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "png", "jpeg"]
                    ),
                ],
            ),
        ),
    ]
