# Generated by Django 4.1.4 on 2023-04-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0166_alter_backupstudent_profile_pic"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BackupStudent",
            new_name="StudentBackup",
        ),
    ]
