# Generated by Django 4.1.4 on 2023-04-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0167_rename_backupstudent_studentbackup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentbackup",
            name="student_idcard_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
