# Generated by Django 4.1.4 on 2023-04-14 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0168_alter_studentbackup_student_idcard_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentbackup",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.student",
            ),
        ),
    ]
