# Generated by Django 4.1.4 on 2023-04-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0172_alter_studentbackup_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="schedule",
        ),
        migrations.AddField(
            model_name="billing",
            name="course_fee",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billing",
            name="course_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="billing",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
