# Generated by Django 4.1.4 on 2023-04-14 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0173_remove_billing_schedule_billing_course_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="course_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.course",
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="sponsor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.sponsor",
            ),
        ),
    ]
