# Generated by Django 4.1.4 on 2023-04-14 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0174_alter_billing_course_name_alter_billing_sponsor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.student",
            ),
        ),
    ]
