# Generated by Django 4.1.4 on 2023-04-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0175_alter_billing_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="billing",
            name="date_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
