# Generated by Django 4.1.4 on 2023-04-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0176_billing_date_posted_billing_date_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarshipsection",
            name="terms_and_conditions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
