# Generated by Django 4.1.4 on 2023-04-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0177_scholarshipsection_terms_and_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcategory",
            name="ordering",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="jobexperience",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="jobexperience",
            name="ordering",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
