# Generated by Django 4.1.4 on 2023-04-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0178_jobcategory_ordering_jobexperience_date_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobcategory",
            options={"ordering": ["-ordering"]},
        ),
        migrations.AlterModelOptions(
            name="jobexperience",
            options={"ordering": ["-ordering"]},
        ),
    ]
