# Generated by Django 4.1.4 on 2023-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0179_alter_jobcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcategory",
            name="ordering",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobexperience",
            name="ordering",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
