# Generated by Django 4.1.4 on 2023-04-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0180_alter_jobcategory_ordering_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="job_ready",
            field=models.BooleanField(default=False),
        ),
    ]
