# Generated by Django 4.1.4 on 2023-04-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0181_student_job_ready"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentbackup",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentbackup",
            name="job_ready",
            field=models.BooleanField(default=False),
        ),
    ]
