# Generated by Django 4.1.4 on 2023-04-18 09:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0182_studentbackup_is_approved_studentbackup_job_ready"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordering", models.PositiveIntegerField()),
                ("main_title", models.CharField(max_length=255)),
                ("main_description", models.TextField()),
                ("event_date", models.DateTimeField(blank=True, null=True)),
                (
                    "image_cover",
                    models.ImageField(
                        upload_to="album/cover/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "svg"]
                            )
                        ],
                    ),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-ordering"],
            },
        ),
        migrations.AlterField(
            model_name="student",
            name="is_approved",
            field=models.BooleanField(
                default=False, help_text="it is used for creating the backup"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="job_ready",
            field=models.BooleanField(
                default=False, help_text="to control student for job applications"
            ),
        ),
        migrations.CreateModel(
            name="AlbumDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordering", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("descriptions", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        upload_to="album/details/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "svg"]
                            )
                        ],
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.album"
                    ),
                ),
            ],
            options={
                "ordering": ["-ordering"],
            },
        ),
    ]
