# Generated by Django 4.1.4 on 2023-04-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0184_alter_album_image_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="main_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
