# Generated by Django 4.1.4 on 2023-04-18 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0185_alter_album_main_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="cv_upload",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="JobPortal/cv_upload",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("pdf",)
                    )
                ],
            ),
        ),
    ]
