# Generated by Django 4.1.4 on 2023-04-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0187_remove_billing_grand_outstanding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingdetail",
            name="amount_paid",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="billingdetail",
            name="billing",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.billing",
            ),
        ),
    ]
