# Generated by Django 4.1.4 on 2023-04-18 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0188_alter_billingdetail_amount_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingdetail",
            name="amount_paid",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billingdetail",
            name="billing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.billing"
            ),
        ),
    ]
