# Generated by Django 4.1.4 on 2023-04-18 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0189_alter_billingdetail_amount_paid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseJobSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("ordering", models.PositiveIntegerField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "ordering": ["-ordering"],
            },
        ),
        migrations.RemoveField(
            model_name="job",
            name="job_location",
        ),
        migrations.RemoveField(
            model_name="job",
            name="job_type",
        ),
        migrations.CreateModel(
            name="JobLocation",
            fields=[
                (
                    "basejobselection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.basejobselection",
                    ),
                ),
            ],
            bases=("api.basejobselection",),
        ),
        migrations.CreateModel(
            name="JobType",
            fields=[
                (
                    "basejobselection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.basejobselection",
                    ),
                ),
            ],
            bases=("api.basejobselection",),
        ),
    ]
