# Generated by Django 4.1.4 on 2023-04-18 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0190_basejobselection_remove_job_job_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.joblocation",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.jobtype",
            ),
        ),
    ]
