# Generated by Django 4.1.4 on 2023-04-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0191_job_job_location_job_job_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentbackup",
            name="student",
        ),
    ]
