# Generated by Django 4.1.4 on 2023-04-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0192_remove_studentbackup_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="careersection",
            old_name="intro_banner",
            new_name="find_your_role",
        ),
        migrations.RenameField(
            model_name="careersection",
            old_name="mission_values",
            new_name="how_we_hire",
        ),
        migrations.RenameField(
            model_name="careersection",
            old_name="our_story",
            new_name="our_culture",
        ),
        migrations.RenameField(
            model_name="careersection",
            old_name="team_description",
            new_name="what_we_offer",
        ),
        migrations.RemoveField(
            model_name="careersection",
            name="is_published",
        ),
    ]
