# Generated by Django 4.1.4 on 2023-04-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0195_alter_album_image_cover_alter_albumdetail_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobcategory",
            options={"ordering": ["ordering"]},
        ),
        migrations.AddField(
            model_name="aboutussection",
            name="join_out_team",
            field=models.TextField(blank=True, null=True),
        ),
    ]
