# Generated by Django 4.1.4 on 2023-04-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0196_alter_jobcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="profile_approval",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
