# Generated by Django 4.1.4 on 2023-04-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0199_alter_employer_kyc_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutussection",
            name="join_out_team",
        ),
        migrations.RemoveField(
            model_name="aboutussection",
            name="why_anchorsoft",
        ),
    ]
