# Generated by Django 4.1.4 on 2023-04-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0200_remove_aboutussection_join_out_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutussection",
            name="join_out_team",
            field=models.TextField(blank=True, null=True),
        ),
    ]
