# Generated by Django 4.1.4 on 2023-04-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0201_aboutussection_join_out_team"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutussection",
            old_name="join_out_team",
            new_name="join_our_team",
        ),
        migrations.RenameField(
            model_name="employer",
            old_name="profile_approval",
            new_name="posting_approval",
        ),
    ]
