# Generated by Django 4.1.4 on 2023-04-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0205_alter_employer_profile_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerapplicant",
            name="highest_qualification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PhD", "PhD"),
                    ("Msc", "Msc"),
                    ("Bsc/B.Tech", "Bsc/B.Tech"),
                    ("HND", "HND"),
                    ("OND/NCE", "OND/NCE"),
                    ("SSCE", "SSCE"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
