# Generated by Django 4.1.4 on 2023-04-20 10:44

import django.core.validators
from django.db import migrations, models

import api.validate


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0206_careerapplicant_highest_qualification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                default="JobPortal/Company/loginIcon.png",
                null=True,
                upload_to="JobPortal/Company",
                validators=[
                    api.validate.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg", "jpg", "png", "jpeg"]
                    ),
                ],
            ),
        ),
    ]
