# Generated by Django 4.1.4 on 2023-04-20 11:00

import api.validate
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0207_alter_employer_company_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employer",
            options={"ordering": ["date_updated"]},
        ),
        migrations.AlterField(
            model_name="employer",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="JobPortal/Company",
                validators=[
                    api.validate.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg", "jpg", "png", "jpeg"]
                    ),
                ],
            ),
        ),
    ]
