# Generated by Django 4.1.4 on 2023-04-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0208_alter_employer_options_alter_employer_company_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employer",
            options={},
        ),
        migrations.AlterField(
            model_name="employer",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
