# Generated by Django 4.1.4 on 2023-04-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0210_alter_job_posting_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentbackup",
            name="student",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.student",
            ),
        ),
    ]
