# Generated by Django 4.1.4 on 2023-05-02 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0212_corporatecoursesection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billingdetail",
            name="course_fee",
        ),
    ]
