# Generated by Django 4.1.4 on 2023-05-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0218_alter_billingdetail_outstanding_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingextrapayment",
            name="outstanding_amount",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
