# Generated by Django 4.1.4 on 2023-05-03 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0220_billingextranameandamount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingextrapayment",
            name="billing_extra_name_and_amount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.billingextranameandamount",
            ),
        ),
    ]
