# Generated by Django 4.1.4 on 2023-05-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0221_billingextrapayment_billing_extra_name_and_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billingextrapayment",
            name="billing",
        ),
        migrations.RemoveField(
            model_name="billingextrapayment",
            name="billing_extra_name_and_amount",
        ),
        migrations.RemoveField(
            model_name="billing",
            name="grand_total_paid",
        ),
        migrations.AddField(
            model_name="billing",
            name="total_amount_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="BillingExtraNameAndAmount",
        ),
        migrations.DeleteModel(
            name="BillingExtraPayment",
        ),
    ]
