# Generated by Django 4.1.4 on 2023-05-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0225_billingdetail_extra_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingdetail",
            name="payment_descriptions",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
