# Generated by Django 4.1.4 on 2023-05-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0226_billingdetail_payment_descriptions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billingdetail",
            name="extra_payment",
        ),
    ]
