# Generated by Django 4.1.4 on 2023-05-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0227_remove_billingdetail_extra_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="total_amount_text",
        ),
    ]
