# Generated by Django 4.1.4 on 2023-05-04 16:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0228_remove_billing_total_amount_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="total_amount_text",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
