# Generated by Django 4.1.4 on 2023-05-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0231_careerapplicant_course_study_careerapplicant_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='course_taken',
        ),
        migrations.AddField(
            model_name='job',
            name='seo_meta_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
