# Generated by Django 4.1.4 on 2023-05-18 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0232_remove_testimonial_course_taken_job_seo_meta_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='course_taken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.course'),
        ),
    ]
