# Generated by Django 4.1.4 on 2023-05-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0233_testimonial_course_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seo_meta_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
