# Generated by Django 4.1.4 on 2023-05-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0235_loanpartner_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='got_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billing',
            name='loanpartner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.loanpartner'),
        ),
        migrations.AddField(
            model_name='student',
            name='got_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='loanpartner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.loanpartner'),
        ),
    ]
