# Generated by Django 4.1.4 on 2023-05-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0236_billing_got_loan_billing_loanpartner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='seo_meta_content',
        ),
        migrations.RemoveField(
            model_name='student',
            name='got_loan',
        ),
        migrations.RemoveField(
            model_name='student',
            name='loanpartner',
        ),
    ]
