# Generated by Django 4.1.4 on 2023-05-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0237_remove_course_seo_meta_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_idcard_id',
        ),
    ]
