# Generated by Django 4.1.4 on 2023-05-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0239_student_matriculation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentBackup',
        ),
    ]
