# Generated by Django 4.1.4 on 2023-05-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0240_delete_studentbackup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='next_of_kin_contact_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='next_of_kin_fullname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='next_of_kin_mobile_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='relationship_with_next_kin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='residential_address',
        ),
    ]
