# Generated by Django 4.1.4 on 2023-05-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0241_remove_student_contact_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_matriculation',
            name='job_ready',
        ),
    ]
