# Generated by Django 4.1.4 on 2023-05-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0242_remove_student_matriculation_job_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
