# Generated by Django 4.1.4 on 2023-05-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0243_seo_page_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='careeropening',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
