# Generated by Django 4.1.4 on 2023-05-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0244_remove_student_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_matriculation',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
