# Generated by Django 4.1.4 on 2023-05-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0247_billing_receipt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='receipt_no',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
