# Generated by Django 4.1.4 on 2023-06-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0250_alter_mainbanner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'ordering': ['ordering']},
        ),
    ]
