# Generated by Django 4.1.4 on 2023-07-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0252_coursewaitinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplicant',
            name='current_salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='careerapplicant',
            name='salary_expectation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
