# Generated by Django 4.1.4 on 2023-07-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0256_alter_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='batch',
        ),
    ]
