# Generated by Django 4.1.4 on 2023-07-23 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0257_remove_question_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.batch'),
        ),
    ]
